### PR TITLE
Update readme.md - required RDMA and JumboPacket change

### PR DESCRIPTION
**Pull request by Karl-WE**
Added Cluster Wizard 
Required Networking settings for MSlab in nested environments

### CODE REVIEW

**Comment by Karl-WE** [comment]
Thanks for you review.

**Comment by jaromirk** [comment]
Its not needed. Internal supplemental package logic will disable rdma for nested environments

**Comment by Karl-WE** [comment]
Honestly I don't trust the workflows.
They are failing for smaller things. Remember DNS servers.

**Comment by jaromirk** [comment]
2405 indeed requires it. Closing this PR, I updated the lab

**Pull request closed without merging**
